saa7160-objs := LINUXV4L2.o wrapper.o property.o tw6805.o cx2581.o sa7160.o sl6010.o tw5864.o fh8735.o ite6603.o mst3367.o mz0380.o  tlv320adc3101.o pl330b.o it1412.o

obj-$(CONFIG_VIDEO_SAA7160) += saa7160.o

ccflags-y +=  -DAME_SA7160

ccflags-y += $(extra-cflags-y) $(extra-cflags-m)
